#!/bin/sh

ssh ubuntu@54.213.16.20 <<EOF
    cd ~/node-app
    git pull origin master
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    source ~/.profile
    nvm install v10.15.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
