#!/bin/sh

ssh ubuntu@172.31.34.244<<EOF
    cd ~/node-app
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    source ~/.bashrc
    nvm install v10.15.3
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
